(()=>{'use strict';
const $=s=>document.querySelector(s),screen=$('#screen'),modal=$('#modal'),box=$('#modalContent'),obj=$('#objectiveText'),toast=$('#toast'),KEY='hamsa-missing-journey-png-v2';
const blank={started:false,scene:'paris',solved:[],clues:[],rabbit:0,drafts:{},seen:{},settings:{sound:true,large:false,contrast:false},finished:false};let S=load(),dialog=null,hint=0;
const scenes={
paris:{chapter:'Prologue',title:'Paris — The Invitation',bg:'assets/scenes/paris-apartment.png',objective:'Inspect Sharon’s changing invitation and pack for Mumbai.',copy:'Sharon’s invitation has begun to erase itself. A tiny white rabbit now appears beside the route.',need:['p1','p2'],next:'cdg',nextText:'Leave for the airport',talk:[['Sharon','Moshé, Leah—come quickly. Leora and I are getting married in Mumbai.'],['Sharon','Bring this invitation. Whatever happens, do not lose the Hamsa.'],['Leah','The venue just disappeared.'],['Moshé','And a rabbit appeared in the corner. Let’s inspect everything.']],spots:[['p1',49,59,'✉','Changing invitation'],['p2',14,72,'▣','Open suitcase'],['map',20,31,'⌁','Travel map','clue'],['r1',86,30,'♧','Rabbit mark','rabbit']]},
cdg:{chapter:'Chapter 1',title:'Paris — Departures',bg:'assets/scenes/paris-airport.png',objective:'Choose the valid Istanbul flight and pass the baggage check.',copy:'The direct Mumbai flight is cancelled. Only one route reaches the Muscat connection in time.',need:['p3','p4'],next:'istanbul',nextText:'Board for Istanbul',talk:[['Leah','I’ll compare the times and delays.'],['Moshé','I’ll check the terminal map.'],['Airport agent','The baggage scale is broken too.']],spots:[['p3',28,24,'▤','Departure board'],['p4',78,67,'⚖','Broken scale'],['r2',55,39,'♧','Rabbit sticker','rabbit']]},
istanbul:{chapter:'Chapter 1',title:'Istanbul — The Hidden Gate',bg:'assets/scenes/istanbul-airport.png',objective:'Align the clocks, restore the tile gate and recover the suitcase.',copy:'Four clocks disagree. The gate is hidden in the blue tiles, and someone has taken the green suitcase.',need:['p5','p6','p7'],next:'muscat',nextText:'Continue to Muscat',talk:[['Moshé','Four cities, four clocks—and none agree.'],['Leah','The tile wall is mechanical.'],['Musician','Are you looking for a green suitcase?']],spots:[['p5',54,42,'◷','Four clocks'],['p6',45,26,'✣','Blue tile gate'],['p7',84,77,'▣','Similar suitcases'],['r3',54,18,'♧','Rabbit mosaic','rabbit']]},
muscat:{chapter:'Chapter 1',title:'Muscat — Under the Stars',bg:'assets/scenes/muscat-airport.png',objective:'Restore the Mumbai gate and assign the final seats.',copy:'A power failure erased the gate display. An old navigation pattern remains on the ceiling.',need:['p8','p9'],next:'mumbai',nextText:'Fly to Mumbai',talk:[['Leah','I can operate the star ceiling.'],['Moshé','I found the route diagram. We need both pieces.']],spots:[['p8',57,18,'✦','Star ceiling'],['p9',79,68,'▦','Seating list'],['r4',90,21,'♧','Rabbit light','rabbit']]},
mumbai:{chapter:'Chapter 1',title:'Mumbai — Two Corridors',bg:'assets/scenes/mumbai-airport.png',objective:'Reunite Leah and Moshé, then find Sharon.',copy:'Security sent them through different corridors. Every control opens the other person’s path.',need:['p10'],next:'memory',nextText:'Follow the rabbit',talk:[['Leah','I can see the power controls, but not the route.'],['Moshé','I can see the doors, but none have power.'],['Unknown message','Two paths. One arrival. Work together.']],spots:[['p10',49,54,'⇄','Linked corridors'],['sharon',53,82,'?','Sharon is missing','clue']]}
};
const puzzles={
p1:{n:'001',title:'The Restless Invitation',cat:'Observation',seal:'Eye Seal',art:[25,0],prompt:'Letters moved when the invitation changed.',inst:'Type the hidden eleven-letter instruction. Spaces do not matter.',type:'text',answer:'TERMINALTWO',hints:['It names an airport location.','It begins with T.','The words contain eight and three letters.','TERMINAL TWO.'],why:'The shifted letters spell TERMINAL TWO.'},
p2:{n:'002',title:'One Suitcase, Two Nomads',cat:'Packing',seal:'Gear Seal',art:[0,25],prompt:'Pack without crushing the wedding gift or burying the passports.',inst:'Enter the item initials in order: Clothes, Scarf box, Kippah case, Shoes, Gift, Food, Chargers, Camera, Toiletries, Passports.',type:'text',answer:'CSKSGFCCTP',hints:['Soft clothes form the base.','The scarf box stays flat.','Passports remain last and accessible.','CSKSGFCCTP.'],why:'The arrangement protects fragile objects and keeps documents accessible.'},
p3:{n:'003',title:'The Flight That Still Exists',cat:'Timetable',seal:'Compass Seal',art:[50,0],prompt:'Only one flight leaves enough time for the Muscat connection.',inst:'Choose the valid itinerary.',type:'choice',answer:'B',options:[['A','09:10 · delayed 55 min · arrives 13:20'],['B','10:05 · on time · arrives 12:55 · same terminal'],['C','09:35 · arrives 12:45 · terminal change needs 70 min']],hints:['The next gate closes at 14:05.','Same-terminal transfer needs 50 minutes.','A is delayed and C changes terminal.','Choose B.'],why:'Flight B reaches Istanbul with enough same-terminal transfer time.'},
p4:{n:'004',title:'The Broken Baggage Scale',cat:'Balance',seal:'Gear Seal',art:[0,75],prompt:'Use exactly three reference weights to balance the 22 kg suitcase.',inst:'Type the weights from largest to smallest, separated by commas.',type:'text',answer:'10,7,5',hints:['Begin with 10 kg.','Add the 7 kg weight.','Five kilograms remain.','10,7,5.'],why:'10 + 7 + 5 = 22 kg.'},
p5:{n:'005',title:'Four Cities, Four Clocks',cat:'Time zones',seal:'Compass Seal',art:[25,75],prompt:'All clocks show the same instant as 09:00 in Paris.',inst:'Enter Istanbul, Muscat and Mumbai times, separated by commas.',type:'text',answer:'11:00,12:00,13:30',hints:['Istanbul is +2 hours.','Muscat is +3 hours.','Mumbai is +4 hours 30.','11:00,12:00,13:30.'],why:'The four clocks now represent the same moment.'},
p6:{n:'006',title:'The Gate in the Tiles',cat:'Pattern',seal:'Eye Seal',art:[50,75],prompt:'The tile wall hides a directional code.',inst:'Tap the symbols in the order Hamsa, Rabbit, Arrow, Gate.',type:'sequence',tokens:['Rabbit','Gate','Hamsa','Arrow'],answer:'HamsaRabbitArrowGate',hints:['Begin with the protective symbol.','The rabbit follows the Hamsa.','The arrow comes before the destination.','Hamsa → Rabbit → Arrow → Gate.'],why:'The completed pattern reveals the hidden concourse.'},
p7:{n:'007',title:'The Vanishing Suitcase',cat:'Deduction',seal:'Key Seal',art:[0,25],prompt:'Who accidentally took the green Mumbai suitcase?',inst:'Use the destination sticker, metal sound and wedding clue.',type:'choice',answer:'musician',options:[['chef','Caterer · spice jars · Ankara'],['student','Student · books · Izmir'],['musician','Musician · metal instruments · Mumbai wedding'],['architect','Architect · plans · Doha']],hints:['The suitcase carries a Mumbai sticker.','A witness heard metal objects.','One suspect is attending Sharon’s wedding.','The musician.'],why:'Only the musician matches every clue.'},
p8:{n:'008',title:'Muscat Under the Stars',cat:'Cooperative route',seal:'Two Hands Seal',art:[75,75],prompt:'Moshé has the route. Leah controls the star ceiling.',inst:'Tap East, Crown, Heart, West, South.',type:'sequence',tokens:['West','Heart','East','South','Crown'],answer:'EastCrownHeartWestSouth',hints:['Begin on the right.','The crown is highest.','The heart is central.','East → Crown → Heart → West → South.'],why:'The route forms a five-finger Hamsa circuit.'},
p9:{n:'009',title:'The Seating Problem',cat:'Logic',seal:'Key Seal',art:[100,75],prompt:'Place seven passengers before the gate closes.',inst:'Enter initials for seats A–G: Moshé, Leah, Sara, Child, Eli, Flowers, Musician.',type:'text',answer:'MLSCEFM',hints:['The family takes C, D and E.','Moshé and Leah take A and B.','Flowers take F and the musician takes G.','MLSCEFM.'],why:'The family stays together and every restriction is satisfied.'},
p10:{n:'010',title:'Two Corridors, One Arrival',cat:'Cooperative finale',seal:'Two Hands Seal',art:[75,0],prompt:'Activate the linked systems in the only safe order.',inst:'Tap the controls in sequence.',type:'sequence',tokens:['Gate','Power','Belt','Walkway','Elevator','Sign'],answer:'PowerGateWalkwayBeltSignElevator',hints:['Leah powers the gate first.','Moshé opens it and redirects the walkway.','The belt changes before the sign.','Power → Gate → Walkway → Belt → Sign → Elevator.'],why:'Each traveler opened the other’s path until both reached arrivals.'}}
;
const anim={idle:[1,0,.1],walk:[7,2,1.15],talk:[5,3,.9],question:[5,4,.9],jump:[5,5,.7],interact:[3,6,.8]};
function load(){try{return {...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(blank)}}function save(){localStorage.setItem(KEY,JSON.stringify(S));apply()}function apply(){document.body.classList.toggle('large',S.settings.large);document.body.classList.toggle('contrast',S.settings.contrast);$('#soundBtn').textContent=S.settings.sound?'♪':'×';$('#soundBtn').setAttribute('aria-pressed',String(!S.settings.sound))}function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2200)}function open(h){box.innerHTML=h;if(!modal.open)modal.showModal()}function close(){if(modal.open)modal.close();box.innerHTML=''}function normalize(v){return String(v||'').toUpperCase().replace(/\s+/g,'').replace(/[–—]/g,'-')}
function title(){obj.textContent='Begin the journey';screen.innerHTML=`<section class="title-screen"><article class="title-card"><img src="assets/ui/app-icon.png" alt="Hamsa"><p class="eyebrow">A cooperative travel mystery</p><h1>Hamsa Nomads <span>The Missing Journey</span></h1><p>Sharon’s wedding invitation is erasing itself. Follow the long route from Paris to Mumbai and recover the memories that brought Leah and Moshé together.</p><button class="primary" id="start">${S.started?'Resume journey':'Begin Chapter 1'}</button>${S.started?'<button class="secondary" id="restart">Start over</button>':''}</article></section>`;$('#start').onclick=()=>{S.started=true;save();render(true)};$('#restart')?.addEventListener('click',()=>{if(confirm('Erase this journey?')){S=structuredClone(blank);save();title()}})}
function char(name,a='idle'){return `<div class="sprite ${name}" data-char="${name}" data-anim="${a}" role="img" aria-label="${name==='leah'?'Leah':'Moshé'}"></div>`}function animate(name,a='idle',reset=0){const e=document.querySelector(`[data-char="${name}"]`),d=anim[a]||anim.idle;if(!e)return;e.dataset.anim=a;e.style.setProperty('--steps',Math.max(1,d[0]-1));e.style.setProperty('--row',`${d[1]/6*100}%`);e.style.setProperty('--speed',`${d[2]}s`);if(reset)setTimeout(()=>animate(name,'idle'),reset)}
function hotspot(x){const[id,l,t,icon,label,kind]=x,done=S.solved.includes(id)||S.clues.includes(id);return `<button class="hotspot ${done?'done':''}" data-id="${id}" data-label="${label}" style="left:${l}%;top:${t}%;transform:translate(-50%,-50%)">${icon}</button>`}
function render(first=false){if(S.scene==='memory')return finale();const s=scenes[S.scene],done=s.need.filter(x=>S.solved.includes(x)).length,complete=done===s.need.length;obj.textContent=s.objective;screen.innerHTML=`<section class="scene"><div class="stage" style="background-image:url('${s.bg}')"><div class="scene-title"><small>${s.chapter}</small><strong>${s.title}</strong></div><div class="character leah">${char('leah')}</div><div class="character moshe">${char('moshe')}</div>${s.spots.map(hotspot).join('')}</div><footer class="scene-info"><h3>${s.title}</h3><p>${s.copy}</p><div class="actions"><button id="talk">Replay scene</button><button id="move">Animate characters</button>${complete?`<button class="next" id="next">${s.nextText} →</button>`:''}</div><div class="progress"><i style="width:${done/s.need.length*100}%"></i></div></footer></section>`;animate('leah');animate('moshe');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>spot(b.dataset.id));$('#talk').onclick=()=>talk(s.talk);$('#move').onclick=()=>{animate('leah','walk',1900);animate('moshe','interact',1900)};$('#next')?.addEventListener('click',()=>{S.scene=s.next;save();render(true)});if(first&&!S.seen[S.scene]){S.seen[S.scene]=1;save();setTimeout(()=>talk(s.talk),250)}}
function talk(lines){dialog={lines,i:0};line()}function line(){document.querySelector('.dialogue')?.remove();if(!dialog||!$('.stage'))return;const[n,t]=dialog.lines[dialog.i],who=n==='Leah'?'leah':n==='Moshé'?'moshe':null;if(who)animate(who,'talk');$('.stage').insertAdjacentHTML('beforeend',`<div class="dialogue"><strong>${n}</strong><p>${t}</p><button aria-label="Next">›</button></div>`);$('.dialogue button').onclick=()=>{if(++dialog.i>=dialog.lines.length){document.querySelector('.dialogue').remove();dialog=null;animate('leah');animate('moshe')}else line()}}
function spot(id){if(puzzles[id]){animate(id==='p2'||id==='p4'?'leah':'moshe','interact',1200);return puzzle(id)}const s=scenes[S.scene],x=s.spots.find(v=>v[0]===id);if(x?.[5]==='rabbit'){if(!S.clues.includes(id)){S.clues.push(id);S.rabbit++;save();say('Rabbit Mark collected');render()}else say('Already collected');return}if(!S.clues.includes(id))S.clues.push(id);save();open(`<div class="section"><p class="eyebrow">Clue discovered</p><h2>${x?.[4]||'Clue'}</h2><p>${id==='map'?'The hand-drawn route links Paris, Istanbul, Muscat and Mumbai.':'No one is waiting at arrivals. A brass Hamsa rests beneath the sign.'}</p></div>`);render()}
function puzzle(id){hint=0;const p=puzzles[id];if(S.solved.includes(id))return solved(id,false);S.drafts[id]??={};open(`<header class="puzzle-head"><div class="puzzle-art" style="--px:${p.art[0]}%;--py:${p.art[1]}%"></div><p class="eyebrow">Puzzle ${p.n} · ${p.cat}</p><h2>${p.title}</h2><p>${p.prompt}</p></header><div class="puzzle"><div class="instructions">${p.inst}</div>${body(id,p)}<div id="hint"></div><div class="feedback" id="feedback"></div><div class="puzzle-buttons"><button class="reset" id="reset">Reset</button><button class="hintbtn" id="hintbtn">Hint</button><button class="submit" id="submit">Submit</button></div></div>`);bind(id,p)}
function body(id,p){const d=S.drafts[id];if(p.type==='choice')return `<div class="options">${p.options.map(([v,l])=>`<label class="option"><input type="radio" name="choice" value="${v}" ${d.value===v?'checked':''}> ${l}</label>`).join('')}</div>`;if(p.type==='sequence'){d.seq??=[];return `<div class="sequence">${p.tokens.map((v,i)=>`<button data-token="${i}" class="${d.seq.includes(i)?'used':''}">${v}</button>`).join('')}</div><p><strong>Selected:</strong> ${d.seq.map(i=>p.tokens[i]).join(' → ')||'none'}</p>`}return `<input id="answer" class="answer" value="${d.value||''}" placeholder="Your answer" autocomplete="off">`}
function bind(id,p){$('#hintbtn').onclick=()=>{hint=Math.min(4,hint+1);$('#hint').innerHTML=`<div class="hint"><strong>Hint ${hint}/4</strong><br>${p.hints[hint-1]}</div>`};$('#reset').onclick=()=>{S.drafts[id]={};save();puzzle(id)};$('#submit').onclick=()=>check(id,p);if(p.type==='choice')document.querySelectorAll('input[name=choice]').forEach(i=>i.onchange=()=>{S.drafts[id].value=i.value;save()});else if(p.type==='sequence')document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const i=+b.dataset.token,a=S.drafts[id].seq;a.includes(i)?a.splice(a.indexOf(i),1):a.push(i);save();puzzle(id)});else $('#answer').oninput=e=>{S.drafts[id].value=e.target.value;save()}}
function check(id,p){const d=S.drafts[id],answer=p.type==='sequence'?d.seq.map(i=>p.tokens[i]).join(''):d.value;if(normalize(answer)===normalize(p.answer)){if(!S.solved.includes(id))S.solved.push(id);delete S.drafts[id];save();solved(id,true)}else $('#feedback').textContent='That does not satisfy every clue yet.'}
function solved(id,newly){const p=puzzles[id];open(`<div class="solution"><img src="assets/ui/app-icon.png" width="78" height="78" alt=""><p class="eyebrow">${newly?'Puzzle solved':'Solved puzzle'}</p><h2>${p.title}</h2><p class="seal">◆ ${p.seal}</p><p>${p.why}</p><button class="primary" id="return">Return to the journey</button></div>`);$('#return').onclick=()=>{close();render();if(newly)say(`${p.seal} added to the passport`)}}
function finale(){S.finished=true;save();obj.textContent='Memory restored: The Rabbit at Havdalah';screen.innerHTML=`<section class="final"><article class="final-card"><img src="assets/ui/app-icon.png" alt="Hamsa"><p class="eyebrow">Chapter 1 complete</p><h1>The Rabbit at Havdalah</h1><div class="memory">Moshé arrived early. He did not expect to see Leah again. His English was not ready—but then a rabbit appeared on the table during Havdalah and gave him the perfect excuse to truly speak to her.</div><p>The first brass-Hamsa fragment returns: <strong>MEETING</strong>. Sharon is still missing.</p><button class="primary" id="chapters">View the next chapter</button></article></section>`;$('#chapters').onclick=chapters}
function passport(){open(`<div class="section"><div class="passport-cover"><img src="assets/ui/app-icon.png" alt=""><h2>Nomad Passport</h2><p>Leah & Moshé · The Missing Journey</p></div><div class="stamp-grid">${[['PARIS','p2'],['ISTANBUL','p7'],['MUSCAT','p9'],['MUMBAI','p10'],['MEETING',S.finished?'yes':'no']].map(([n,k])=>`<div class="stamp ${(k==='yes'||S.solved.includes(k))?'':'locked'}"><strong>${n}</strong></div>`).join('')}</div><p><strong>${S.solved.length}/10</strong> puzzles · <strong>${S.rabbit}</strong> Rabbit Marks</p></div>`)}
function route(){const order=['paris','cdg','istanbul','muscat','mumbai','memory'],i=order.indexOf(S.scene);open(`<div class="section"><p class="eyebrow">The long way east</p><h2>Journey Route</h2><div class="route">${[['Paris','Invitation'],['Paris Airport','Departure'],['Istanbul','Hidden gate'],['Muscat','Star route'],['Mumbai','Two corridors'],['Havdalah','Memory']].map((x,n)=>`<div class="stop ${n<=i||S.finished?'done':''}"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></div>`)}
function mysteries(){const rows=[['Why is the invitation changing?',S.solved.includes('p1')],['Why does the rabbit keep appearing?',S.finished],['Why was Sharon absent?',false],['Who was erased from the photograph?',false],['What is inside the brass Hamsa?',S.finished]];open(`<div class="section"><p class="eyebrow">Investigation notebook</p><h2>Mysteries</h2><div class="cards">${rows.map(([q,d])=>`<div class="card ${d?'done':''}"><strong>${d?'✓ ':''}${q}</strong></div>`).join('')}</div></div>`)}
function settings(){open(`<div class="section"><p class="eyebrow">Accessibility</p><h2>Settings</h2><div class="cards"><label class="card settings-row">Sound cues <input data-set="sound" type="checkbox" ${S.settings.sound?'checked':''}></label><label class="card settings-row">Larger text <input data-set="large" type="checkbox" ${S.settings.large?'checked':''}></label><label class="card settings-row">High contrast <input data-set="contrast" type="checkbox" ${S.settings.contrast?'checked':''}></label></div></div>`);document.querySelectorAll('[data-set]').forEach(x=>x.onchange=()=>{S.settings[x.dataset.set]=x.checked;save()})}
function chapters(){open(`<div class="section"><p class="eyebrow">Journey chapters</p><h2>The story ahead</h2><div class="cards"><div class="card done"><strong>Chapter 1 · Three Flights East</strong><p>Paris → Istanbul → Muscat → Mumbai</p></div><div class="card"><strong>Chapter 2 · The Wedding Without a Seventh Blessing</strong><p>Mumbai wedding, Indian Jewish traditions and a missing ceremonial page.</p></div><div class="card"><strong>Chapter 3 · The City of Doubles</strong><p>Elephanta Caves, Ahmedabad and the first memories of Israel.</p></div><div class="card"><strong>Later chapters</strong><p>Udaipur, Pushkar, Jaipur, Agra, the Himalayas and the true proposal.</p></div></div></div>`)}
$('#modalClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};$('#passportBtn').onclick=passport;$('#mapBtn').onclick=route;$('#journalBtn').onclick=mysteries;$('#settingsBtn').onclick=settings;$('#objectiveBtn').onclick=()=>open(`<div class="section"><p class="eyebrow">Current objective</p><h2>${scenes[S.scene]?.title||'The Missing Journey'}</h2><p>${scenes[S.scene]?.objective||'Remember the journey.'}</p></div>`);$('#soundBtn').onclick=()=>{S.settings.sound=!S.settings.sound;save();say(S.settings.sound?'Sound enabled':'Sound muted')};$('#homeBtn').onclick=title;apply();S.started?render():title();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();