(()=>{'use strict';
const $=s=>document.querySelector(s),screen=$('#screen'),modal=$('#modal'),content=$('#modalContent'),objective=$('#objectiveText'),toast=$('#toast'),KEY='our-story-game-v1';
const fresh={started:false,scene:'paris',solved:[],rabbit:0,clues:[],draft:{},seen:{},settings:{sound:true,large:false,contrast:false},finished:false};
let state=load(),dialogue=null,hintStep=0;
const scenes={
paris:{chapter:'Prologue',title:'Paris — The Invitation',bg:'assets/scenes/paris-apartment.svg',objective:'Inspect Sharon’s changing invitation and prepare for Mumbai.',copy:'The direct route has disappeared. A rabbit symbol now sits in the corner of Sharon’s invitation.',req:['p1','p2'],next:'cdg',nextLabel:'Leave for the airport',dialogue:[['Sharon','Moshé, Leah—come quickly. Leora and I are getting married in Mumbai.'],['Sharon','Bring this invitation with you. And whatever happens, do not lose the Hamsa.'],['Leah','The address just disappeared.'],['Moshé','And a rabbit appeared in the corner. We should inspect everything.']],spots:[['p1',49,57,'✉','Changing invitation'],['p2',14,69,'▣','Open suitcase'],['map',21,28,'⌁','Travel map','clue'],['r1',87,29,'rabbit','Rabbit mark','rabbit']]},
cdg:{chapter:'Chapter 1',title:'Paris — Departures',bg:'assets/scenes/paris-airport.svg',objective:'Find the valid Istanbul flight and get the suitcase accepted.',copy:'The direct Mumbai flight is cancelled. Only one itinerary reaches Muscat before boarding closes.',req:['p3','p4'],next:'istanbul',nextLabel:'Board for Istanbul',dialogue:[['Leah','I will compare the times and delays.'],['Moshé','I will check the terminal map.'],['Airport Agent','The baggage scale is also broken.']],spots:[['p3',26,25,'▤','Departure board'],['p4',79,66,'⚖','Broken scale'],['r2',52,37,'rabbit','Rabbit sticker','rabbit']]},
istanbul:{chapter:'Chapter 1',title:'Istanbul — The Hidden Gate',bg:'assets/scenes/istanbul-airport.svg',objective:'Find the hidden gate and recover the suitcase.',copy:'Four clocks disagree, the gate is hidden in the tiles, and a musician has your suitcase.',req:['p5','p6','p7'],next:'muscat',nextLabel:'Continue to Muscat',dialogue:[['Moshé','Four clocks, four cities—and none of them agree.'],['Leah','The tile wall has movable sections.'],['Musician','Are you looking for a green suitcase?']],spots:[['p5',76,22,'◷','Four clocks'],['p6',25,43,'✣','Blue tile gate'],['p7',74,74,'▣','Similar suitcases'],['r3',43,19,'rabbit','Rabbit mosaic','rabbit']]},
muscat:{chapter:'Chapter 1',title:'Muscat — Under the Stars',bg:'assets/scenes/muscat-airport.svg',objective:'Restore the Mumbai gate and assign the final seats.',copy:'The power failure erased the gate. An older navigation pattern remains above you.',req:['p8','p9'],next:'mumbai',nextLabel:'Fly to Mumbai',dialogue:[['Leah','The star points control the lighting system.'],['Moshé','I found the route diagram. We need both pieces.']],spots:[['p8',57,19,'✦','Star ceiling'],['p9',79,67,'▦','Seating list'],['r4',90,20,'rabbit','Rabbit light','rabbit']]},
mumbai:{chapter:'Chapter 1',title:'Mumbai — Two Corridors',bg:'assets/scenes/mumbai-airport.svg',objective:'Reunite Leah and Moshé and find Sharon.',copy:'Security sent Leah and Moshé through different corridors. Each path controls the other.',req:['p10'],next:'memory',nextLabel:'Follow the rabbit',dialogue:[['Leah','I can see the power controls, but not the route.'],['Moshé','I can see the doors, but none of them have power.'],['Unknown Message','Two paths. One arrival. Work together.']],spots:[['p10',50,54,'⇄','Linked corridors'],['sharon',50,82,'?','Sharon is missing','clue']]}}
;
const puzzles={
p1:{n:'001',title:'The Restless Invitation',cat:'Observation',seal:'Eye Seal',prompt:'Letters moved when Sharon’s invitation changed.',inst:'Type the hidden eleven-letter instruction. Spaces are ignored.',type:'text',answer:'TERMINALTWO',placeholder:'Hidden message',hints:['It names a place inside the airport.','It begins with T.','The words have eight and three letters.','TERMINAL TWO.'],why:'The moved letters form TERMINAL TWO.'},
p2:{n:'002',title:'One Suitcase, Two Nomads',cat:'Packing',seal:'Gear Seal',prompt:'Pack without burying the passports or crushing the gift.',inst:'Type the first letter of each item in correct packing order: Clothes, Scarf box, Kippah case, Shoes, Gift, Food, Chargers, Camera, Toiletries, Passports.',type:'text',answer:'CSKSGFCCTP',placeholder:'Packing code',hints:['Soft clothes form the base.','The scarf box goes before shoes.','Passports must remain last.','CSKSGFCCTP.'],why:'Soft items protect the base, the gift remains cushioned, and passports stay accessible.'},
p3:{n:'003',title:'The Flight That Still Exists',cat:'Timetable',seal:'Compass Seal',prompt:'Only one flight leaves enough time for the Muscat connection.',inst:'Choose the valid itinerary.',type:'choice',answer:'B',options:[['A','09:10 · delayed 55 min · arrives 13:20'],['B','10:05 · on time · arrives 12:55 · same terminal'],['C','09:35 · arrives 12:45 · terminal change requires 70 min']],hints:['The gate closes at 14:05.','Same-terminal transfer needs 50 minutes.','A is too delayed; C changes terminal.','Choose B.'],why:'Flight B reaches Istanbul with enough same-terminal transfer time.'},
p4:{n:'004',title:'The Broken Baggage Scale',cat:'Balance',seal:'Gear Seal',prompt:'Use exactly three reference weights to balance the 22 kg suitcase.',inst:'Type the three weights from largest to smallest, separated by commas.',type:'text',answer:'10,7,5',placeholder:'10,7,5',hints:['Use the largest weight.','Add 7 kg to 10 kg.','You need 5 kg more.','10,7,5.'],why:'10 + 7 + 5 = 22 kg.'},
p5:{n:'005',title:'Four Cities, Four Clocks',cat:'Time zones',seal:'Compass Seal',prompt:'All clocks show the same instant as 09:00 in Paris.',inst:'Enter Istanbul, Muscat and Mumbai times in HH:MM format, separated by commas.',type:'text',answer:'11:00,12:00,13:30',placeholder:'11:00,12:00,13:30',hints:['Istanbul is +2h.','Muscat is +3h.','Mumbai is +4h30.','11:00,12:00,13:30.'],why:'The clocks now represent the same moment across four cities.'},
p6:{n:'006',title:'The Gate in the Tiles',cat:'Spatial',seal:'Eye Seal',prompt:'Rotate the nine directory tiles until every line stands upright.',inst:'Tap each tile until all tiles return to their original orientation.',type:'tiles',hints:['Each tap rotates 90°.','Start with corners.','All tiles share one final orientation.','Set every tile to 0°.'],why:'The aligned pattern reveals a hamsa, rabbit and gate arrow.'},
p7:{n:'007',title:'The Vanishing Suitcase',cat:'Deduction',seal:'Key Seal',prompt:'Who accidentally took the green Mumbai suitcase?',inst:'Use the metal sounds, destination sticker and wedding clue.',type:'choice',answer:'musician',options:[['chef','The Caterer · spice jars · Ankara'],['student','The Student · books · Izmir'],['musician','The Musician · metal instruments · Mumbai wedding'],['architect','The Architect · plans · Doha']],hints:['The bag has a Mumbai sticker.','A witness heard metal objects.','One suspect is going to Sharon’s wedding.','The musician.'],why:'Only the musician matches all three pieces of evidence.'},
p8:{n:'008',title:'Muscat Under the Stars',cat:'Cooperative route',seal:'Two Hands Seal',prompt:'Moshé has the route; Leah controls the star ceiling.',inst:'Tap the sequence East, Crown, Heart, West, South.',type:'sequence',tokens:['E','C','H','W','S'],answer:'ECHWS',hints:['Begin on the right.','The Crown is highest.','The Heart is central.','E → C → H → W → S.'],why:'The star route forms the five-finger hamsa circuit.'},
p9:{n:'009',title:'The Seating Problem',cat:'Logic',seal:'Key Seal',prompt:'Place seven passengers before the gate closes.',inst:'Enter seats A–G as initials: Moshé, Leah, Sara, Child, Eli, Flowers, Musician.',type:'text',answer:'MLSCEFM',placeholder:'MLSCEFM',hints:['The family takes C,D,E.','Moshé and Leah take A,B.','Flowers take F; musician takes G.','MLSCEFM.'],why:'The family stays together, Leah has aisle access, and the musician gets a window.'},
p10:{n:'010',title:'Two Corridors, One Arrival',cat:'Cooperative finale',seal:'Two Hands Seal',prompt:'Activate the linked systems in the only safe order.',inst:'Tap the controls in sequence. Wrong actions do not erase progress.',type:'sequence',tokens:['Power','Gate','Walkway','Belt','Sign','Elevator'],answer:'PowerGateWalkwayBeltSignElevator',hints:['Leah powers the gate first.','Moshé opens it and redirects the walkway.','Leah reverses the belt before the sign changes.','Power → Gate → Walkway → Belt → Sign → Elevator.'],why:'Each traveler opened the other’s path until both reached the same arrivals hall.'}}
;
function load(){try{return {...fresh,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(fresh)}}function save(){localStorage.setItem(KEY,JSON.stringify(state));apply()}function apply(){document.body.classList.toggle('large',state.settings.large);document.body.classList.toggle('contrast',state.settings.contrast);$('#soundBtn').textContent=state.settings.sound?'♪':'×'}function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2200)}function open(html){content.innerHTML=html;if(!modal.open)modal.showModal()}function close(){if(modal.open)modal.close();content.innerHTML=''}
function title(){objective.textContent='Begin the journey';screen.innerHTML=`<section class="title-screen"><div class="title-card"><img src="assets/ui/hamsa.svg" alt="Hamsa"><p class="eyebrow">A cooperative travel mystery</p><h1>Hamsa Nomads <span>The Missing Journey</span></h1><p>Sharon’s wedding invitation is erasing itself. Follow the long route from Paris to Mumbai, solve the clues together, and recover the memories that brought Leah and Moshé to each other.</p><button class="primary" id="start">${state.started?'Resume journey':'Begin Chapter 1'}</button>${state.started?'<button class="secondary" id="restart">Start over</button>':''}</div></section>`;$('#start').onclick=()=>{state.started=true;save();render(true)};$('#restart')?.addEventListener('click',()=>{if(confirm('Erase this journey?')){state=structuredClone(fresh);save();title()}})}
function render(play=false){if(state.scene==='memory')return finale();const s=scenes[state.scene];objective.textContent=s.objective;const done=s.req.filter(x=>state.solved.includes(x)).length,complete=done===s.req.length;screen.innerHTML=`<section class="scene"><div class="stage" style="background-image:url('${s.bg}')"><div class="scene-title"><small>${s.chapter}</small><strong>${s.title}</strong></div><div class="character leah"><img src="assets/characters/leah.svg" alt="Leah"></div><div class="character moshe"><img src="assets/characters/moshe.svg" alt="Moshé"></div>${s.spots.map(x=>spot(x)).join('')}</div><div class="scene-info"><h3>${s.title}</h3><p>${s.copy}</p><div class="scene-actions"><button id="talk">Replay scene</button><button id="points">Show points</button>${complete?`<button class="next" id="next">${s.nextLabel} →</button>`:''}</div><div class="progress"><i style="width:${s.req.length?done/s.req.length*100:100}%"></i></div></div></section>`;document.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>handleSpot(b.dataset.spot));$('#talk').onclick=()=>talk(s.dialogue);$('#points').onclick=()=>document.querySelectorAll('.hotspot').forEach(h=>h.animate([{scale:1},{scale:1.3},{scale:1}],{duration:650}));$('#next')?.addEventListener('click',()=>{state.scene=s.next;save();render(true)});if(play&&!state.seen[state.scene]){state.seen[state.scene]=1;save();setTimeout(()=>talk(s.dialogue),300)}}
function spot(x){const[id,left,top,icon,label,kind]=x,done=state.solved.includes(id)||state.clues.includes(id);return `<button data-spot="${id}" data-label="${label}" class="hotspot ${kind||''} ${done?'done':''}" style="left:${left}%;top:${top}%;transform:translate(-50%,-50%)">${icon==='rabbit'?'<img src="assets/ui/rabbit.svg" alt="">':icon}</button>`}
function talk(lines){dialogue={lines,i:0};line()}function line(){document.querySelector('.dialogue')?.remove();const stage=$('.stage');if(!stage||!dialogue)return;const[n,t]=dialogue.lines[dialogue.i];stage.insertAdjacentHTML('beforeend',`<div class="dialogue"><strong>${n}</strong><p>${t}</p><button aria-label="Next">›</button></div>`);$('.dialogue button').onclick=()=>{if(++dialogue.i>=dialogue.lines.length){$('.dialogue').remove();dialogue=null}else line()}}
function handleSpot(id){if(puzzles[id])return puzzle(id);const s=scenes[state.scene],x=s.spots.find(v=>v[0]===id),kind=x?.[5];if(kind==='rabbit'){if(!state.clues.includes(id)){state.clues.push(id);state.rabbit++;save();showToast('Rabbit Mark collected');render()}else showToast('Already collected');return}if(!state.clues.includes(id))state.clues.push(id);save();open(`<div class="modal-section"><p class="subtitle">Clue discovered</p><h2>${x?.[4]||'Clue'}</h2><p>${id==='map'?'The hand-drawn route links Paris, Istanbul, Muscat and Mumbai.':'No one is waiting at arrivals. A brass hamsa lies beneath the sign.'}</p></div>`);render()}
function puzzle(id){hintStep=0;const p=puzzles[id];if(state.solved.includes(id))return solved(id,false);state.draft[id]??={};open(`<div class="puzzle-intro"><p class="subtitle">Puzzle ${p.n} · ${p.cat}</p><h2>${p.title}</h2><p>${p.prompt}</p></div><div class="puzzle"><div class="instructions">${p.inst}</div>${body(id,p)}<div id="hint"></div><div class="feedback" id="feedback"></div><div class="puzzle-buttons"><button class="reset" id="reset">Reset</button><button class="hintbtn" id="hintbtn">Hint</button><button class="submit" id="submit">Submit answer</button></div></div>`);bind(id,p)}
function body(id,p){const d=state.draft[id];if(p.type==='choice')return `<div class="options">${p.options.map(([v,l])=>`<label class="option"><input type="radio" name="choice" value="${v}" ${d.value===v?'checked':''}>${l}</label>`).join('')}</div>`;if(p.type==='tiles'){d.tiles??=[1,2,3,1,3,2,1,2,3];return `<div class="tile-grid">${d.tiles.map((r,i)=>`<button class="tile" data-tile="${i}" data-r="${r}" aria-label="Rotate tile ${i+1}"></button>`).join('')}</div>`}if(p.type==='sequence'){d.seq??=[];return `<div class="sequence">${p.tokens.map((v,i)=>`<button data-token="${i}" class="${d.seq.includes(i)?'used':''}">${v}</button>`).join('')}</div><p><strong>Selected:</strong> ${d.seq.map(i=>p.tokens[i]).join(' → ')||'none'}</p>`}return `<input class="answer-input" id="answer" value="${d.value||''}" placeholder="${p.placeholder||'Your answer'}" autocomplete="off">`}
function bind(id,p){$('#hintbtn').onclick=()=>{hintStep=Math.min(4,hintStep+1);$('#hint').innerHTML=`<div class="hint"><strong>Hint ${hintStep}/4</strong><br>${p.hints[hintStep-1]}</div>`};$('#reset').onclick=()=>{state.draft[id]={};save();puzzle(id)};$('#submit').onclick=()=>check(id,p);if(p.type==='choice')document.querySelectorAll('input[name=choice]').forEach(i=>i.onchange=()=>{state.draft[id].value=i.value;save()});else if(p.type==='tiles')document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{let i=+b.dataset.tile;state.draft[id].tiles[i]=(state.draft[id].tiles[i]+1)%4;save();puzzle(id)});else if(p.type==='sequence')document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const i=+b.dataset.token,d=state.draft[id].seq;if(d.includes(i))d.splice(d.indexOf(i),1);else d.push(i);save();puzzle(id)});else $('#answer').oninput=e=>{state.draft[id].value=e.target.value;save()}}
function norm(v){return String(v||'').toUpperCase().replace(/\s+/g,'').replace(/[–—]/g,'-')}function check(id,p){let ok=false,d=state.draft[id];if(p.type==='tiles')ok=d.tiles.every(x=>x===0);else if(p.type==='sequence')ok=d.seq.map(i=>p.tokens[i]).join('')===p.answer;else ok=norm(d.value)===norm(p.answer);if(ok){if(!state.solved.includes(id))state.solved.push(id);delete state.draft[id];save();solved(id,true)}else $('#feedback').textContent='That does not satisfy every clue yet. Compare the evidence and try again.'}
function solved(id,newly){const p=puzzles[id];open(`<div class="solution"><img src="assets/ui/hamsa.svg" alt=""><p class="subtitle">${newly?'Puzzle solved':'Solved puzzle'}</p><h2>${p.title}</h2><div class="seal">◆ ${p.seal}</div><p>${p.why}</p><button class="primary" id="return">Return to the journey</button></div>`);$('#return').onclick=()=>{close();render();if(newly)showToast(`${p.seal} added to the passport`)}}
function finale(){state.finished=true;save();objective.textContent='Memory restored: The Rabbit at Havdalah';screen.innerHTML=`<section class="final"><article class="final-card"><img src="assets/ui/rabbit.svg" alt="White rabbit"><p class="eyebrow">Chapter 1 complete</p><h1>The Rabbit at Havdalah</h1><div class="memory">Moshé arrived early. He did not expect to see Leah again. His English was not ready—but his heart was louder. Then a rabbit appeared on the table during Havdalah and gave him the perfect excuse to truly speak to her.</div><p>The first brass-hamsa fragment returns: <strong>MEETING</strong>. Sharon is still missing, and the erased wedding photograph remains unexplained.</p><button class="primary" id="chapters">View the next chapter</button></article></section>`;$('#chapters').onclick=chapterList}
function passport(){open(`<div class="modal-section"><div class="passport-cover"><img src="assets/ui/hamsa.svg" alt=""><h2>Nomad Passport</h2><p>Leah & Moshé · The Missing Journey</p></div><div class="stamp-grid">${[['PARIS','p2'],['ISTANBUL','p7'],['MUSCAT','p9'],['MUMBAI','p10'],['MEETING',state.finished?'yes':'no']].map(([n,k])=>`<div class="stamp ${(k==='yes'||state.solved.includes(k))?'':'locked'}"><strong>${n}</strong></div>`).join('')}</div><p><strong>${state.solved.length}/10</strong> puzzles · <strong>${state.rabbit}</strong> Rabbit Marks</p></div>`)}
function route(){const order=['paris','cdg','istanbul','muscat','mumbai','memory'],i=order.indexOf(state.scene);open(`<div class="modal-section"><p class="subtitle">The long way east</p><h2>Journey Route</h2><div class="route">${[['Paris','Invitation'],['Paris Airport','Departure'],['Istanbul','Hidden gate'],['Muscat','Star route'],['Mumbai','Two corridors'],['Havdalah','Memory']].map((x,n)=>`<div class="stop ${n<=i||state.finished?'done':''}"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></div>`)}
function mysteries(){const rows=[['Why is the invitation changing?',state.solved.includes('p1')],['Why does the rabbit keep appearing?',state.finished],['Why was Sharon absent?',false],['Who was erased from the photograph?',false],['What is inside the brass hamsa?',state.finished]];open(`<div class="modal-section"><p class="subtitle">Investigation notebook</p><h2>Mysteries</h2><div class="cards">${rows.map(([q,d])=>`<div class="card ${d?'done':''}"><strong>${d?'✓ ':''}${q}</strong></div>`).join('')}</div></div>`)}
function settings(){open(`<div class="modal-section"><p class="subtitle">Accessibility</p><h2>Settings</h2><div class="cards"><label class="card">Sound cues <input data-set="sound" type="checkbox" ${state.settings.sound?'checked':''}></label><label class="card">Larger text <input data-set="large" type="checkbox" ${state.settings.large?'checked':''}></label><label class="card">High contrast <input data-set="contrast" type="checkbox" ${state.settings.contrast?'checked':''}></label></div></div>`);document.querySelectorAll('[data-set]').forEach(x=>x.onchange=()=>{state.settings[x.dataset.set]=x.checked;save()})}
function chapterList(){open(`<div class="modal-section"><p class="subtitle">Journey chapters</p><h2>The story ahead</h2><div class="cards"><div class="card done"><strong>Chapter 1 · Three Flights East</strong><p>Paris → Istanbul → Muscat → Mumbai</p></div><div class="card"><strong>Chapter 2 · The Wedding Without a Seventh Blessing</strong><p>Mumbai wedding, Indian Jewish traditions and a missing ceremonial page.</p></div><div class="card"><strong>Chapter 3 · The City of Doubles</strong><p>Elephanta Caves, Ahmedabad and the first memories of Israel.</p></div><div class="card"><strong>Later chapters</strong><p>Udaipur, Pushkar, Jaipur, Agra, the Himalayas and the true proposal.</p></div></div></div>`)}
$('#modalClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};$('#passportBtn').onclick=passport;$('#mapBtn').onclick=route;$('#journalBtn').onclick=mysteries;$('#settingsBtn').onclick=settings;$('#objectiveBtn').onclick=()=>open(`<div class="modal-section"><p class="subtitle">Current objective</p><h2>${scenes[state.scene]?.title||'The Missing Journey'}</h2><p>${scenes[state.scene]?.objective||'Remember the journey.'}</p></div>`);$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save();showToast(state.settings.sound?'Sound enabled':'Sound muted')};$('#homeBtn').onclick=title;apply();state.started?render():title();
})();